// Build data/members.json: the one school list the front end reads.
//
// The site needs each school's crest, county, athletic director and - crucially -
// its SCHEDULE url, and those live in three different places: schools.json has the
// scheduler link, directory.json has the AD and the crest filename, and the crest
// files themselves are on disk. Rather than have every page join those at runtime,
// join them once here and let the pages read one file.
//
// Run as part of the schedule workflow so a school added to schools.json shows up
// on the site without anyone remembering to regenerate anything.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const read = p => JSON.parse(fs.readFileSync(path.join(ROOT, p), 'utf8'));

const schools = read('data/schools.json').schools;
const directory = read('data/directory.json').directory;
const LOGO_DIR = 'images/logos/optimized';
const logos = fs.readdirSync(path.join(ROOT, LOGO_DIR)).filter(f => f.endsWith('.png')).map(f => f.replace('.png', ''));

// Which county each school sits in. Not present in any data file, and it drives
// the footer grouping and the schools-page filter.
const SUSSEX = ['high-point', 'hopatcong', 'kittatinny', 'lenape-valley', 'newton', 'pope-john', 'sparta', 'sussex-county-school-of-technology', 'vernon', 'wallkill-valley'];
const WARREN = ['hackettstown', 'north-warren'];

// Names the site shows instead of the long official ones.
const SHORT = {
    'academy-saint-elizabeth': 'Saint Elizabeth',
    'morris-county-school-of-technology': 'Morris County Tech',
    'sussex-county-school-of-technology': 'Sussex County Tech',
    'morristown-beard': 'Morristown-Beard',
    'pope-john': 'Pope John XXIII',
};

const norm = s => String(s || '').toLowerCase()
    .replace(/\b(high school|hs|school|academy|township|twp|of|the|regional|xxiii|county|technology|tech)\b/g, '')
    .replace(/[^a-z]/g, '');

// A bare DigitalSports subdomain answers 403 - in a real browser, not just to
// scripts - while the schedule is served from a fixed path beneath it. Several
// schools are recorded as the bare root, so normalise or those links are dead.
const schedUrl = u => !u ? ''
    : /^https?:\/\/[^/]*digitalsports\.com\/?$/i.test(u) ? u.replace(/\/?$/, '/pages/schedule/schedule.php')
    : u;

const members = directory.map(d => {
    const slug = String(d.logo || '').replace('.png', '');
    if (!slug || !logos.includes(slug)) throw new Error(`no crest for ${d.school} (looked for ${slug}.png)`);
    const s = schools.find(x => norm(x.name) === norm(d.school)) || {};
    return {
        name: d.school,
        short: SHORT[slug] || d.school.replace(/ High School$/, '').replace(/ School$/, '').replace(/ Academy$/, '').replace(/ Township$/, ''),
        slug,
        county: SUSSEX.includes(slug) ? 'Sussex' : WARREN.includes(slug) ? 'Warren' : 'Morris',
        logo: `${LOGO_DIR}/${slug}.png`,
        website: s.website || d.website || '',
        schedule: schedUrl(s.arbiterUrl),
        ad: d.ad || '',
        email: d.email || '',
        phone: d.phone || '',
    };
}).sort((a, b) => a.short.localeCompare(b.short));

const counties = members.reduce((a, m) => { a[m.county] = (a[m.county] || 0) + 1; return a; }, {});

fs.writeFileSync(path.join(ROOT, 'data/members.json'), JSON.stringify({
    _comment: 'Generated by scripts/build-members.js from schools.json + directory.json. Do not edit by hand.',
    conference: 'Northwest Jersey Athletic Conference',
    abbr: 'NJAC',
    tagline: 'A Tradition of Excellence',
    generated: new Date().toISOString(),
    counties,
    members,
}, null, 2) + '\n');

const noSchedule = members.filter(m => !m.schedule).map(m => m.short);
console.log(`members.json: ${members.length} schools (${Object.entries(counties).map(([k, v]) => `${k} ${v}`).join(', ')})`);
console.log(`  with AD: ${members.filter(m => m.ad).length}  with schedule link: ${members.filter(m => m.schedule).length}`);
if (noSchedule.length) console.log(`  NO schedule url: ${noSchedule.join(', ')}`);
